/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ComplianceGate",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ComplianceGate__factory>;
    getContractFactory(
      name: "FeeRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FeeRouter__factory>;
    getContractFactory(
      name: "FiatToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FiatToken__factory>;
    getContractFactory(
      name: "IComplianceGate",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IComplianceGate__factory>;
    getContractFactory(
      name: "IFeeRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFeeRouter__factory>;
    getContractFactory(
      name: "ReserveRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReserveRegistry__factory>;

    getContractAt(
      name: "ComplianceGate",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ComplianceGate>;
    getContractAt(
      name: "FeeRouter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FeeRouter>;
    getContractAt(
      name: "FiatToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FiatToken>;
    getContractAt(
      name: "IComplianceGate",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IComplianceGate>;
    getContractAt(
      name: "IFeeRouter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFeeRouter>;
    getContractAt(
      name: "ReserveRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReserveRegistry>;

    deployContract(
      name: "ComplianceGate",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ComplianceGate>;
    deployContract(
      name: "FeeRouter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FeeRouter>;
    deployContract(
      name: "FiatToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FiatToken>;
    deployContract(
      name: "IComplianceGate",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IComplianceGate>;
    deployContract(
      name: "IFeeRouter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFeeRouter>;
    deployContract(
      name: "ReserveRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReserveRegistry>;

    deployContract(
      name: "ComplianceGate",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ComplianceGate>;
    deployContract(
      name: "FeeRouter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FeeRouter>;
    deployContract(
      name: "FiatToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FiatToken>;
    deployContract(
      name: "IComplianceGate",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IComplianceGate>;
    deployContract(
      name: "IFeeRouter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFeeRouter>;
    deployContract(
      name: "ReserveRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReserveRegistry>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
