/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IComplianceGate,
  IComplianceGateInterface,
} from "../../FiatToken.sol/IComplianceGate";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "meta",
        type: "bytes",
      },
    ],
    name: "preTransferCheck",
    outputs: [
      {
        internalType: "bool",
        name: "allowed",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "code",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IComplianceGate__factory {
  static readonly abi = _abi;
  static createInterface(): IComplianceGateInterface {
    return new Interface(_abi) as IComplianceGateInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IComplianceGate {
    return new Contract(address, _abi, runner) as unknown as IComplianceGate;
  }
}
