/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFeeRouter,
  IFeeRouterInterface,
} from "../../FiatToken.sol/IFeeRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "onTransfer",
    outputs: [
      {
        internalType: "uint256",
        name: "feeAmount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFeeRouter__factory {
  static readonly abi = _abi;
  static createInterface(): IFeeRouterInterface {
    return new Interface(_abi) as IFeeRouterInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IFeeRouter {
    return new Contract(address, _abi, runner) as unknown as IFeeRouter;
  }
}
